wordpress:
  image: wordpress
  links:
    - mysql
  environment:
     - WORDPRESS_DB_PASSWORD=password
  ports:
    - 8080:80
  volumes:
    - .:/var/www/html/wp-content/plugins/external-videos

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=wordpress
